server:
  port: 8081
  servlet:
    context-path: /exercise

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/identity_service?useSSL=false
    username: mysql
    password: P@ssword123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
